# Name of the action
name: Run tests

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events on `dev` branch
  push:
    branches: [ github_actions ]
  pull_request:
    branches: [ github_actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]

    # Define a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so job can access it
      - name: Clone the repo and checkout `dev` branch
        uses: actions/checkout@v1

      # Use Node.js
      - name: Use Node version 12.19.0
        uses: actions/setup-node@v1
        with:
          node-version: "12.19.0"

      # Run a set of commands for testing using the runners shell
      - name: Run tests
        env:
            TEST_KEY: ${{ secrets.TEST_AUTOMATION_SECRET }}
        run: |
          printf "$TEST_KEY\n" > .env        # Generate the environment file
          npm install                        # Install NPM packages
          python3 scripts/test.py --backend  # Run backend tests 
